# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', path: '.', url: 'index.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'News', path: 'menu', url: 'news.html'}
- {name: 'Educations', path: 'menu', url: 'educations.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'CV', path: 'assets', url: 'cv.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/jiesongk'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/jiesongk/'}
- {icon: 'envelope', link: 'mailto:jiesongk@umich.edu'}
# - {icon: 'phone', link: 'tel:+1 734-546-4113'}
- {icon: 'address-card', link: 'https://goo.gl/maps/Dedu1i1bCJG2'}


# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
